Repository avirajdongare/BooleanAutocrats, pull requests merged in 2022-10, with the labels that each got.

#39 sudoku Using C++
  SUDOKU.CPP
Labels: hacktoberfest-accepted

#44 Added Ping Pong Game
  Classic Ping Pong/Ball.class
  Classic Ping Pong/Brick.class
  Classic Ping Pong/Pong.class
  Classic Ping Pong/Pong.htm
  Classic Ping Pong/Pong.java
  Classic Ping Pong/Wall.class
  Classic Ping Pong/back.jpg
  Classic Ping Pong/back1.jpg
  Classic Ping Pong/ball.gif
  Classic Ping Pong/ball1.gif
  Classic Ping Pong/brick.gif
  Classic Ping Pong/gameover.gif
  Classic Ping Pong/gong.au
  Classic Ping Pong/hitpad.au
  Classic Ping Pong/hitwall.au
  Classic Ping Pong/logo.gif
  Classic Ping Pong/pad.gif
  Classic Ping Pong/pad1.gif
  Classic Ping Pong/title.gif
Labels: enhancement, Hacktoberfest2022, hacktoberfest-accepted

#43 Added ASCII video generator in terminal
  ASCII Video Generator/main.py
Labels: Hacktoberfest2022

#42 Added gesture volume control program
  Volume_Gesture_Control/main.py
Labels: Hacktoberfest2022, hacktoberfest-accepted

#46 added password generator
  password_generator/main.py
Labels: Hacktoberfest2022, hacktoberfest-accepted

#53 LOGIN System Using php and DB
  loginsystem/forgetpass.php
  loginsystem/login.php
  loginsystem/loginid.sql
  loginsystem/logout.php
  loginsystem/signup.php
  loginsystem/welcome.php
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted

#58 added solution for Monty Hall problem
  Monty_hall/main.py
Labels: Hacktoberfest, hacktoberfest-accepted

#61 Create vaccum-clearner-agent.py
  vaccum-clearner-agent.py
Labels: Hacktoberfest, hacktoberfest-accepted

#75 Added person detection using python
  Person Detection/person.py
Labels: Hacktoberfest, hacktoberfest-accepted

#68 Music Player GUI
  MusicPlayer.py
Labels: hacktoberfest

#57 Added Ripple Button Effect Project
  Ripple Button Effect/index.html
  Ripple Button Effect/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#72 rakshabandhan webpage added
  rakhiwebsite/bg.png
  rakhiwebsite/index.html
  rakhiwebsite/rakhifinal.png
  rakhiwebsite/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#78 Added text-extractor scripts
  text-extractor/README.md
  text-extractor/decode_predictions.py
  text-extractor/images/its_ok.png
  text-extractor/main.py
  text-extractor/requirements.txt
Labels: hacktoberfest, hacktoberfest-accepted

#80 coinflip.py
  coinflip.py
Labels: documentation, enhancement

#84 created 3D graph using matplotlib
  3D_graph_using_matplotlib
Labels: hacktoberfest, hacktoberfest-accepted

#85 Created Blackjack Game In Python
  blackjack
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#87 Integrated OpenCV program into Streamlit
  openCV_project
Labels: hacktoberfest, hacktoberfest-accepted

#86 deployed AI chatbot using HTML
  AI_chatbot
Labels: documentation, help wanted, hacktoberfest, hacktoberfest-accepted

#77 Added Rock Paper Scissors Game using Python
  Rock_Paper_Scissors_Game.py
Labels: hacktoberfest, hacktoberfest-accepted

#54 Asteroid Game
  Asteroid.c.cpp
  PIANO.CPP
Labels: hacktoberfest, hacktoberfest-accepted

#96 Added invisible cloak
  Harry Potter/invisible_cloak.py
Labels: hacktoberfest, hacktoberfest-accepted

#97 Added handwritten character program
  handwritten_character.py
Labels: hacktoberfest, hacktoberfest-accepted

#93 ranning effect using html and css
  ranning effect/css/styles.css
  ranning effect/index.html
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#99 diwali wishing card using hover effect
  happydiwalihovereffect/css/styles.css
  happydiwalihovereffect/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#103 Hangman game
  hangman_game.py
Labels: hacktoberfest, hacktoberfest-accepted
